x-flink-common:
  &flink-common
  image: flink
  environment:
    - HADOOP_CONF_DIR=/opt/flink/conf
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager
      metrics.reporters: prom
      metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
      metrics.reporter.prom.port: 9091
      fs.allowed-fallback-filesystems: s3;s3a
      classloader.resolve-order: parent-first
  networks:
    - data-net

services:
  jobmanager:
    # build: .
    <<: *flink-common
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      # - ./flink/jobs:/opt/flink/jobs
      # - ./flink/src:/opt/flink/src
      - ./flink/sql:/opt/flink/sql
      - ./flink/target:/opt/flink/target
      # - ./flink/pom.xml:/opt/flink/pom.xml
      - ./flink/conf/core-site.xml:/opt/flink/conf/core-site.xml
  taskmanager:
    # build: .
    <<: *flink-common
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
          replicas: 2
    volumes:
      - ./flink/conf/core-site.xml:/opt/flink/conf/core-site.xml

networks:
  data-net:
    external: true
